language: python
python:
  - "2.6"
  - "2.7"
  - "3.4"
install:
  - pip install -e . --use-mirrors --download-cache $HOME/.pip-cache/
  - pip install -e ".[tests]" --use-mirrors --download-cache $HOME/.pip-cache/
script:
  - make unit
